/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spacevent.spacevent_desktop.Vista;

import com.spacevent.spacevent_desktop.Controlador.DevolucionControlador;
import com.spacevent.spacevent_desktop.Controlador.ReservaAsesorControlador;
import com.spacevent.spacevent_desktop.Controlador.LoginControlador;
import com.spacevent.spacevent_desktop.Controlador.ReservaAdminControlador;
import com.spacevent.spacevent_desktop.Controlador.VisitaAdminControlador;
import com.spacevent.spacevent_desktop.Controlador.VisitaAsesorControlador;
import com.spacevent.spacevent_desktop.Modelo.ContratoConsulta;
import com.spacevent.spacevent_desktop.Modelo.Detalle_Pago;
import com.spacevent.spacevent_desktop.Modelo.Detalle_PagoConsulta;
import com.spacevent.spacevent_desktop.Modelo.Devolucion;
import com.spacevent.spacevent_desktop.Modelo.DevolucionConsulta;
import com.spacevent.spacevent_desktop.Modelo.LocalConsulta;
import com.spacevent.spacevent_desktop.Modelo.Pago;
import com.spacevent.spacevent_desktop.Modelo.PagoConsulta;
import com.spacevent.spacevent_desktop.Modelo.Personal;
import com.spacevent.spacevent_desktop.Modelo.PersonalConsulta;
import com.spacevent.spacevent_desktop.Modelo.Reserva;
import com.spacevent.spacevent_desktop.Modelo.ReservaConsulta;
import com.spacevent.spacevent_desktop.Modelo.Usuario;
import com.spacevent.spacevent_desktop.Modelo.UsuarioConsulta;
import com.spacevent.spacevent_desktop.Modelo.Visita;
import com.spacevent.spacevent_desktop.Modelo.VisitaConsulta;

/**
 *
 * @author Usuario
 */
public class OpcionAdmin extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesAsesor
     */
    public OpcionAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPersonas = new javax.swing.JButton();
        btnVisita = new javax.swing.JButton();
        btnAtrassss = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnDevoluciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPersonas.setBackground(new java.awt.Color(153, 153, 255));
        btnPersonas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonas.setText("Personas");
        btnPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 60));

        btnVisita.setBackground(new java.awt.Color(153, 153, 255));
        btnVisita.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnVisita.setForeground(new java.awt.Color(255, 255, 255));
        btnVisita.setText("Visitas");
        btnVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 180, 150));

        btnAtrassss.setBackground(new java.awt.Color(102, 204, 255));
        btnAtrassss.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtrassss.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrassss.setText("<- Atras");
        btnAtrassss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrassssActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtrassss, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        btnReservas.setBackground(new java.awt.Color(153, 153, 255));
        btnReservas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnReservas.setText("Reservas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });
        jPanel1.add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 180, 150));

        btnDevoluciones.setBackground(new java.awt.Color(153, 153, 255));
        btnDevoluciones.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btnDevoluciones.setText("Devoluciones");
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 180, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonasActionPerformed
        this.dispose();
        OpcionesPersona frm = new OpcionesPersona();
        frm.setVisible(true);
    }//GEN-LAST:event_btnPersonasActionPerformed

    private void btnVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitaActionPerformed
        this.dispose();
        VisitaAdminControlador ctrl = new VisitaAdminControlador(new Visita(), new VisitaConsulta(), new VisitaAdminVista());
        ctrl.iniciar();
        ctrl.getFrm().setVisible(true);
    }//GEN-LAST:event_btnVisitaActionPerformed

    private void btnAtrassssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrassssActionPerformed
        this.dispose();
        LoginControlador ctrl = new LoginControlador(new LoginVista(), new Personal(), new PersonalConsulta());
        ctrl.iniciar();
        ctrl.getfrm().setVisible(true);

    }//GEN-LAST:event_btnAtrassssActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        this.dispose();
        ReservaAdminControlador ctrl = new ReservaAdminControlador(
                new ReservaAdminVista(),
                new Reserva(),
                new ReservaConsulta(),
                new ContratoConsulta(),
                new Usuario(),
                new UsuarioConsulta(),
                new LocalConsulta(),
                new Pago(),
                new PagoConsulta(),
                new Detalle_Pago(),
                new Detalle_PagoConsulta());
        ctrl.iniciar();
        ctrl.getFrm().setVisible(true);

    }//GEN-LAST:event_btnReservasActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        this.dispose();
        DevolucionControlador ctrl = new DevolucionControlador(new DevolucionConsulta(), new DevolucionAdmin());
        ctrl.iniciar();
        ctrl.getFrm().setVisible(true);
    }//GEN-LAST:event_btnDevolucionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtrassss;
    public javax.swing.JButton btnDevoluciones;
    public javax.swing.JButton btnPersonas;
    public javax.swing.JButton btnReservas;
    public javax.swing.JButton btnVisita;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
