/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spacevent.spacevent_desktop.Vista;

/**
 *
 * @author Usuario
 */
public class VisitaAsesorVista extends javax.swing.JFrame {

    /**
     * Creates new form VisitaAsesor
     */
    public VisitaAsesorVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVisitante = new javax.swing.JTable();
        btnVisitaRealizada = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEnviarContrato = new javax.swing.JButton();
        btnCancelado = new javax.swing.JButton();
        btnPendiente = new javax.swing.JButton();
        btnVisitaProgramada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 60));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Visitas Asignadas");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtVisitante.setBackground(new java.awt.Color(255, 255, 255));
        jtVisitante.setForeground(new java.awt.Color(0, 0, 0));
        jtVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtVisitante);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 550, 460));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 550, 500));

        btnVisitaRealizada.setBackground(new java.awt.Color(153, 51, 255));
        btnVisitaRealizada.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnVisitaRealizada.setForeground(new java.awt.Color(255, 255, 255));
        btnVisitaRealizada.setText("Visita Realizada");
        btnVisitaRealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitaRealizadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisitaRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 180, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 170, 40));

        btnAtras.setBackground(new java.awt.Color(102, 204, 255));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("<- Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        btnEnviarContrato.setBackground(new java.awt.Color(0, 204, 0));
        btnEnviarContrato.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnEnviarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarContrato.setText("Enviar Contrato");
        btnEnviarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarContratoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 170, 40));

        btnCancelado.setBackground(new java.awt.Color(153, 51, 255));
        btnCancelado.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCancelado.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelado.setText("Cancelado");
        btnCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceladoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 120, 40));

        btnPendiente.setBackground(new java.awt.Color(153, 51, 255));
        btnPendiente.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnPendiente.setForeground(new java.awt.Color(255, 255, 255));
        btnPendiente.setText("Pendiente");
        btnPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 120, 40));

        btnVisitaProgramada.setBackground(new java.awt.Color(153, 51, 255));
        btnVisitaProgramada.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnVisitaProgramada.setForeground(new java.awt.Color(255, 255, 255));
        btnVisitaProgramada.setText("Visita Programada");
        btnVisitaProgramada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitaProgramadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisitaProgramada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        OpcionAsesor frm = new OpcionAsesor();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVisitaRealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitaRealizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisitaRealizadaActionPerformed

    private void btnEnviarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarContratoActionPerformed

    private void btnCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanceladoActionPerformed

    private void btnPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendienteActionPerformed

    private void btnVisitaProgramadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitaProgramadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisitaProgramadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitaAsesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitaAsesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitaAsesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitaAsesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitaAsesorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnCancelado;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEnviarContrato;
    public javax.swing.JButton btnPendiente;
    public javax.swing.JButton btnVisitaProgramada;
    public javax.swing.JButton btnVisitaRealizada;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtVisitante;
    // End of variables declaration//GEN-END:variables
}
